name: pandas_wkshp2
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=2.2.2=py_0
  - ipywidgets=7.4.*
  - matplotlib=2.2.*
  - pandas=0.23.*
  - pip=18.0=py36_1
  - python=3.6.*
  - vega=2.0.0=py36_0
  - vega_datasets=0.5.0=py_0
  
